### ISSUE TITLE
Do not hide section of size < 20 

### ISSUE THREAD

**Issue by KanedaFr** [raulgotor/linkerscope#26]
Hi again,

since we have to total control over what to draw or not using `hide-xxxx`, is this code still needed ?
https://github.com/raulgotor/linkerscope/blob/d74f20fb71916d6c4cacc912cbeeb96606379c3c/map_render.py#L498

I recently used `hide-name: true` and  `hide-size: true` only to show the end address of a memory section:
sectionA starts at 0xFFF8 but is only 8 bytes
sectionB starts at 0x2000 and so ends when sectionA starts

my goal was to draw something like
```
sectionA ------- |.             | 0xFFF8
                 |.             |  
...
                 |. secA        |  
...
                 |.             |  0x2000
                 ---------  
```

(using link for sectionA)

It took me 2hours to understand why my 0xFFF8 wasn't printed :( 
I do understand address's text could overlap and section name won't fit on a less than 20 pixels section, but it locks an interesting use case

....unless there is another way to do it I missed again!

**Comment by raulgotor** [comment]
Quickly implemented it: [PR](https://github.com/raulgotor/linkerscope/pull/28), please check it out.

Now, `hidde-xxxx` can be `yes`, `no` or `auto` with `auto` as default. `true` and `false` are kept for backwards compatibility.
